version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.test
    image: rws/api:latest
    container_name: rws-api
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - .:/var/rws-api
      - /var/rws-api/node_modules
    ports:
      - "4000:4000"
    tty: true
    command: npm run test

  mongodb:
    image: mongo
    container_name: rws-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db

volumes:
  mongodb_test_data:
#
#
# Running tests:
# --------------
# docker-compose -f docker-compose.test.yml up [--build] --exit-code-from api
